# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCachingInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=32, verbose_name='Project Name')),
                ('project_id', models.CharField(max_length=32, verbose_name='Project ID')),
                ('cpu_type', models.CharField(max_length=32, default='CPU 1.0', verbose_name='CPU Type', choices=[('CPU 1.0', 'CPU 1.0'), ('CPU 1.1', 'CPU 1.1')])),
                ('reference_link', models.URLField(default='http://10.100.8.185:8090', verbose_name='Reference Link (Confluence)')),
                ('neck_cpu', models.BooleanField(verbose_name='CPU Neck')),
                ('neck_io', models.BooleanField(verbose_name='IO Neck')),
                ('neck_memory', models.BooleanField(verbose_name='Memory Neck')),
                ('neck_net', models.BooleanField(verbose_name='Net Neck')),
                ('test_application', models.CharField(max_length=32, editable=False, default='Data Caching')),
                ('version', models.CharField(max_length=10, default='0.1', verbose_name='Application Version')),
                ('record_result_time', models.DateTimeField(verbose_name='Record Result Time', default=django.utils.timezone.now)),
                ('result_max_rps', models.FloatField(verbose_name='Result - Max RPS')),
                ('data_scale', models.PositiveSmallIntegerField(verbose_name='Data Scale')),
                ('number_works', models.PositiveSmallIntegerField(verbose_name='Work Number')),
                ('number_connections', models.PositiveSmallIntegerField(verbose_name='Connection Number')),
                ('number_threads', models.PositiveSmallIntegerField(verbose_name='Thread Number')),
                ('network_bandwidth', models.PositiveSmallIntegerField(verbose_name='Network Bandwidth (Mbps)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataCachingMachine',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('machine_side', models.CharField(max_length=32, default='server_side', verbose_name='Server/Client', choices=[('server_side', 'As a Server'), ('client_side', 'As a Client')])),
                ('machine_name', models.CharField(max_length=32, default='Habonaro', verbose_name='Machine Name', choices=[('Habonaro', 'Habonaro'), ('Palmetto', 'Palmetto'), ('S812L', 'S812L'), ('S822L', 'S822L'), ('X86_E5', 'X86 E5 Series')])),
                ('architecture_type', models.CharField(max_length=32, default='powerpc', verbose_name='Architecture', choices=[('x86', 'x86'), ('powerpc', 'powerpc'), ('arm64', 'arm64'), ('mips', 'mips')])),
                ('byte_order', models.CharField(max_length=32, default='big_endian', verbose_name='Litter or Big endian', choices=[('litter_endian', 'Litter Endian'), ('big_endian', 'Big Endian')])),
                ('cpu_frequency', models.FloatField(verbose_name='CPU Clock Rate (GHZ)')),
                ('l1_instruction', models.PositiveSmallIntegerField(verbose_name='L1 I-Cache (KB)')),
                ('l1_data', models.PositiveSmallIntegerField(verbose_name='L1 D-Cache (KB)')),
                ('l2', models.PositiveSmallIntegerField(verbose_name='L2 Cache (KB)')),
                ('l3', models.PositiveIntegerField(verbose_name='L3 Cache (KB)', blank=True, default=0)),
                ('l4', models.PositiveIntegerField(verbose_name='L4 Cache (KB)', blank=True, default=0)),
                ('memory', models.PositiveIntegerField(verbose_name='Memory (MB)')),
                ('os_type', models.CharField(max_length=64, default='Ubuntu 14.04.2', verbose_name='Operation System', choices=[('Ubuntu 14.04.1', 'Ubuntu 14.04.1'), ('Ubuntu 14.04.2', 'Ubuntu 14.04.2'), ('Ubuntu 14.04.3', 'Ubuntu 14.04.3'), ('Ubuntu 14.04.10', 'Ubuntu 14.04.10'), ('RHEL 7.0', 'RHEL 7.0'), ('CentOS 6.6', 'CentOS 6.6'), ('CentOS 6.7', 'CentOS 6.7'), ('CentOS 7.0', 'CentOS 7.0'), ('Fedora 22', 'Fedora 22'), ('PowerKVM 2.1.1', 'PowerKVM 2.1.1')])),
                ('kernel_version', models.CharField(max_length=64, default='3.16.0', verbose_name='Kernel Version', choices=[('2.6.32', '2.6.32'), ('3.10.0', '3.10.0'), ('3.10.53', '3.10.53'), ('3.10.89', '3.10.89'), ('3.13.0', '3.13.0'), ('3.16.0', '3.16.0'), ('3.19.0', '3.19.0'), ('4.0.4', '4.0.4'), ('4.1.0', '4.1.0')])),
                ('dependence_information', models.TextField(max_length=1024, blank=True, verbose_name='Dependency Instruction')),
                ('last_modify_time', models.DateTimeField(verbose_name='Last Modified Time', auto_now=True)),
                ('app_information', models.ForeignKey(to='performance.DataCachingInformation', verbose_name='DataCaching Information')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LmbenchInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=32, verbose_name='Project Name')),
                ('project_id', models.CharField(max_length=32, verbose_name='Project ID')),
                ('cpu_type', models.CharField(max_length=32, default='CPU 1.0', verbose_name='CPU Type', choices=[('CPU 1.0', 'CPU 1.0'), ('CPU 1.1', 'CPU 1.1')])),
                ('reference_link', models.URLField(default='http://10.100.8.185:8090', verbose_name='Reference Link (Confluence)')),
                ('neck_cpu', models.BooleanField(verbose_name='CPU Neck')),
                ('neck_io', models.BooleanField(verbose_name='IO Neck')),
                ('neck_memory', models.BooleanField(verbose_name='Memory Neck')),
                ('neck_net', models.BooleanField(verbose_name='Net Neck')),
                ('test_application', models.CharField(max_length=32, editable=False, default='Lmbench')),
                ('version', models.CharField(max_length=10, default='0.1', verbose_name='Application Version')),
                ('record_result_time', models.DateTimeField(verbose_name='Record Result Time', default=django.utils.timezone.now)),
                ('result_time', models.FloatField(verbose_name='Result - Time')),
                ('app_name', models.CharField(max_length=256, default='bw_mem', verbose_name='app name')),
                ('problem_size', models.CharField(max_length=256, verbose_name='Problem Size')),
                ('thread_number', models.PositiveSmallIntegerField(verbose_name='Thread Number')),
                ('node', models.CharField(max_length=256, verbose_name='Node')),
                ('phycpu', models.CharField(max_length=256, verbose_name='Physical CPU')),
                ('stride_size', models.PositiveIntegerField(verbose_name='Stride Size (Byte)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LmbenchMachine',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('machine_side', models.CharField(max_length=32, default='server_side', verbose_name='Server/Client', choices=[('server_side', 'As a Server'), ('client_side', 'As a Client')])),
                ('machine_name', models.CharField(max_length=32, default='Habonaro', verbose_name='Machine Name', choices=[('Habonaro', 'Habonaro'), ('Palmetto', 'Palmetto'), ('S812L', 'S812L'), ('S822L', 'S822L'), ('X86_E5', 'X86 E5 Series')])),
                ('architecture_type', models.CharField(max_length=32, default='powerpc', verbose_name='Architecture', choices=[('x86', 'x86'), ('powerpc', 'powerpc'), ('arm64', 'arm64'), ('mips', 'mips')])),
                ('byte_order', models.CharField(max_length=32, default='big_endian', verbose_name='Litter or Big endian', choices=[('litter_endian', 'Litter Endian'), ('big_endian', 'Big Endian')])),
                ('cpu_frequency', models.FloatField(verbose_name='CPU Clock Rate (GHZ)')),
                ('l1_instruction', models.PositiveSmallIntegerField(verbose_name='L1 I-Cache (KB)')),
                ('l1_data', models.PositiveSmallIntegerField(verbose_name='L1 D-Cache (KB)')),
                ('l2', models.PositiveSmallIntegerField(verbose_name='L2 Cache (KB)')),
                ('l3', models.PositiveIntegerField(verbose_name='L3 Cache (KB)', blank=True, default=0)),
                ('l4', models.PositiveIntegerField(verbose_name='L4 Cache (KB)', blank=True, default=0)),
                ('memory', models.PositiveIntegerField(verbose_name='Memory (MB)')),
                ('os_type', models.CharField(max_length=64, default='Ubuntu 14.04.2', verbose_name='Operation System', choices=[('Ubuntu 14.04.1', 'Ubuntu 14.04.1'), ('Ubuntu 14.04.2', 'Ubuntu 14.04.2'), ('Ubuntu 14.04.3', 'Ubuntu 14.04.3'), ('Ubuntu 14.04.10', 'Ubuntu 14.04.10'), ('RHEL 7.0', 'RHEL 7.0'), ('CentOS 6.6', 'CentOS 6.6'), ('CentOS 6.7', 'CentOS 6.7'), ('CentOS 7.0', 'CentOS 7.0'), ('Fedora 22', 'Fedora 22'), ('PowerKVM 2.1.1', 'PowerKVM 2.1.1')])),
                ('kernel_version', models.CharField(max_length=64, default='3.16.0', verbose_name='Kernel Version', choices=[('2.6.32', '2.6.32'), ('3.10.0', '3.10.0'), ('3.10.53', '3.10.53'), ('3.10.89', '3.10.89'), ('3.13.0', '3.13.0'), ('3.16.0', '3.16.0'), ('3.19.0', '3.19.0'), ('4.0.4', '4.0.4'), ('4.1.0', '4.1.0')])),
                ('dependence_information', models.TextField(max_length=1024, blank=True, verbose_name='Dependency Instruction')),
                ('last_modify_time', models.DateTimeField(verbose_name='Last Modified Time', auto_now=True)),
                ('app_information', models.ForeignKey(to='performance.LmbenchInformation', verbose_name='Lmbench Information')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParsecInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=32, verbose_name='Project Name')),
                ('project_id', models.CharField(max_length=32, verbose_name='Project ID')),
                ('cpu_type', models.CharField(max_length=32, default='CPU 1.0', verbose_name='CPU Type', choices=[('CPU 1.0', 'CPU 1.0'), ('CPU 1.1', 'CPU 1.1')])),
                ('reference_link', models.URLField(default='http://10.100.8.185:8090', verbose_name='Reference Link (Confluence)')),
                ('neck_cpu', models.BooleanField(verbose_name='CPU Neck')),
                ('neck_io', models.BooleanField(verbose_name='IO Neck')),
                ('neck_memory', models.BooleanField(verbose_name='Memory Neck')),
                ('neck_net', models.BooleanField(verbose_name='Net Neck')),
                ('test_application', models.CharField(max_length=32, editable=False, default='Parsec')),
                ('version', models.CharField(max_length=10, default='0.1', verbose_name='Application Version')),
                ('record_result_time', models.DateTimeField(verbose_name='Record Result Time', default=django.utils.timezone.now)),
                ('result_time', models.FloatField(verbose_name='Result - Time(s)')),
                ('app_name', models.CharField(max_length=256, verbose_name='app name')),
                ('input_set', models.CharField(max_length=256, verbose_name='Input Set')),
                ('thread_number', models.PositiveSmallIntegerField(verbose_name='Thread Number')),
                ('smt_number', models.PositiveSmallIntegerField(verbose_name='SMT')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParsecMachine',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('machine_side', models.CharField(max_length=32, default='server_side', verbose_name='Server/Client', choices=[('server_side', 'As a Server'), ('client_side', 'As a Client')])),
                ('machine_name', models.CharField(max_length=32, default='Habonaro', verbose_name='Machine Name', choices=[('Habonaro', 'Habonaro'), ('Palmetto', 'Palmetto'), ('S812L', 'S812L'), ('S822L', 'S822L'), ('X86_E5', 'X86 E5 Series')])),
                ('architecture_type', models.CharField(max_length=32, default='powerpc', verbose_name='Architecture', choices=[('x86', 'x86'), ('powerpc', 'powerpc'), ('arm64', 'arm64'), ('mips', 'mips')])),
                ('byte_order', models.CharField(max_length=32, default='big_endian', verbose_name='Litter or Big endian', choices=[('litter_endian', 'Litter Endian'), ('big_endian', 'Big Endian')])),
                ('cpu_frequency', models.FloatField(verbose_name='CPU Clock Rate (GHZ)')),
                ('l1_instruction', models.PositiveSmallIntegerField(verbose_name='L1 I-Cache (KB)')),
                ('l1_data', models.PositiveSmallIntegerField(verbose_name='L1 D-Cache (KB)')),
                ('l2', models.PositiveSmallIntegerField(verbose_name='L2 Cache (KB)')),
                ('l3', models.PositiveIntegerField(verbose_name='L3 Cache (KB)', blank=True, default=0)),
                ('l4', models.PositiveIntegerField(verbose_name='L4 Cache (KB)', blank=True, default=0)),
                ('memory', models.PositiveIntegerField(verbose_name='Memory (MB)')),
                ('os_type', models.CharField(max_length=64, default='Ubuntu 14.04.2', verbose_name='Operation System', choices=[('Ubuntu 14.04.1', 'Ubuntu 14.04.1'), ('Ubuntu 14.04.2', 'Ubuntu 14.04.2'), ('Ubuntu 14.04.3', 'Ubuntu 14.04.3'), ('Ubuntu 14.04.10', 'Ubuntu 14.04.10'), ('RHEL 7.0', 'RHEL 7.0'), ('CentOS 6.6', 'CentOS 6.6'), ('CentOS 6.7', 'CentOS 6.7'), ('CentOS 7.0', 'CentOS 7.0'), ('Fedora 22', 'Fedora 22'), ('PowerKVM 2.1.1', 'PowerKVM 2.1.1')])),
                ('kernel_version', models.CharField(max_length=64, default='3.16.0', verbose_name='Kernel Version', choices=[('2.6.32', '2.6.32'), ('3.10.0', '3.10.0'), ('3.10.53', '3.10.53'), ('3.10.89', '3.10.89'), ('3.13.0', '3.13.0'), ('3.16.0', '3.16.0'), ('3.19.0', '3.19.0'), ('4.0.4', '4.0.4'), ('4.1.0', '4.1.0')])),
                ('dependence_information', models.TextField(max_length=1024, blank=True, verbose_name='Dependency Instruction')),
                ('last_modify_time', models.DateTimeField(verbose_name='Last Modified Time', auto_now=True)),
                ('app_information', models.ForeignKey(to='performance.ParsecInformation', verbose_name='Parsec Information')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiriusSuitInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=32, verbose_name='Project Name')),
                ('project_id', models.CharField(max_length=32, verbose_name='Project ID')),
                ('cpu_type', models.CharField(max_length=32, default='CPU 1.0', verbose_name='CPU Type', choices=[('CPU 1.0', 'CPU 1.0'), ('CPU 1.1', 'CPU 1.1')])),
                ('reference_link', models.URLField(default='http://10.100.8.185:8090', verbose_name='Reference Link (Confluence)')),
                ('neck_cpu', models.BooleanField(verbose_name='CPU Neck')),
                ('neck_io', models.BooleanField(verbose_name='IO Neck')),
                ('neck_memory', models.BooleanField(verbose_name='Memory Neck')),
                ('neck_net', models.BooleanField(verbose_name='Net Neck')),
                ('test_application', models.CharField(max_length=32, editable=False, default='Sirius-suit')),
                ('version', models.CharField(max_length=10, default='0.1', verbose_name='Application Version')),
                ('record_result_time', models.DateTimeField(verbose_name='Record Result Time', default=django.utils.timezone.now)),
                ('result_run_time', models.FloatField(verbose_name='Result - RUN_TIME(ms)')),
                ('result_passed', models.BooleanField(verbose_name='Result - PASSED')),
                ('result_warnings', models.BooleanField(verbose_name='Result - WARNINGS')),
                ('result_errors', models.BooleanField(verbose_name='Result - ERRORS')),
                ('app_name', models.CharField(max_length=256, verbose_name='app name')),
                ('pthread_num', models.PositiveSmallIntegerField(verbose_name='Pthread Number')),
                ('dataset_size', models.FloatField(verbose_name='Dataset Size (GB)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiriusSuitMachine',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('machine_side', models.CharField(max_length=32, default='server_side', verbose_name='Server/Client', choices=[('server_side', 'As a Server'), ('client_side', 'As a Client')])),
                ('machine_name', models.CharField(max_length=32, default='Habonaro', verbose_name='Machine Name', choices=[('Habonaro', 'Habonaro'), ('Palmetto', 'Palmetto'), ('S812L', 'S812L'), ('S822L', 'S822L'), ('X86_E5', 'X86 E5 Series')])),
                ('architecture_type', models.CharField(max_length=32, default='powerpc', verbose_name='Architecture', choices=[('x86', 'x86'), ('powerpc', 'powerpc'), ('arm64', 'arm64'), ('mips', 'mips')])),
                ('byte_order', models.CharField(max_length=32, default='big_endian', verbose_name='Litter or Big endian', choices=[('litter_endian', 'Litter Endian'), ('big_endian', 'Big Endian')])),
                ('cpu_frequency', models.FloatField(verbose_name='CPU Clock Rate (GHZ)')),
                ('l1_instruction', models.PositiveSmallIntegerField(verbose_name='L1 I-Cache (KB)')),
                ('l1_data', models.PositiveSmallIntegerField(verbose_name='L1 D-Cache (KB)')),
                ('l2', models.PositiveSmallIntegerField(verbose_name='L2 Cache (KB)')),
                ('l3', models.PositiveIntegerField(verbose_name='L3 Cache (KB)', blank=True, default=0)),
                ('l4', models.PositiveIntegerField(verbose_name='L4 Cache (KB)', blank=True, default=0)),
                ('memory', models.PositiveIntegerField(verbose_name='Memory (MB)')),
                ('os_type', models.CharField(max_length=64, default='Ubuntu 14.04.2', verbose_name='Operation System', choices=[('Ubuntu 14.04.1', 'Ubuntu 14.04.1'), ('Ubuntu 14.04.2', 'Ubuntu 14.04.2'), ('Ubuntu 14.04.3', 'Ubuntu 14.04.3'), ('Ubuntu 14.04.10', 'Ubuntu 14.04.10'), ('RHEL 7.0', 'RHEL 7.0'), ('CentOS 6.6', 'CentOS 6.6'), ('CentOS 6.7', 'CentOS 6.7'), ('CentOS 7.0', 'CentOS 7.0'), ('Fedora 22', 'Fedora 22'), ('PowerKVM 2.1.1', 'PowerKVM 2.1.1')])),
                ('kernel_version', models.CharField(max_length=64, default='3.16.0', verbose_name='Kernel Version', choices=[('2.6.32', '2.6.32'), ('3.10.0', '3.10.0'), ('3.10.53', '3.10.53'), ('3.10.89', '3.10.89'), ('3.13.0', '3.13.0'), ('3.16.0', '3.16.0'), ('3.19.0', '3.19.0'), ('4.0.4', '4.0.4'), ('4.1.0', '4.1.0')])),
                ('dependence_information', models.TextField(max_length=1024, blank=True, verbose_name='Dependency Instruction')),
                ('last_modify_time', models.DateTimeField(verbose_name='Last Modified Time', auto_now=True)),
                ('app_information', models.ForeignKey(to='performance.SiriusSuitInformation', verbose_name='Sirius-suit Information')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SparkTerasortInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=32, verbose_name='Project Name')),
                ('project_id', models.CharField(max_length=32, verbose_name='Project ID')),
                ('cpu_type', models.CharField(max_length=32, default='CPU 1.0', verbose_name='CPU Type', choices=[('CPU 1.0', 'CPU 1.0'), ('CPU 1.1', 'CPU 1.1')])),
                ('reference_link', models.URLField(default='http://10.100.8.185:8090', verbose_name='Reference Link (Confluence)')),
                ('neck_cpu', models.BooleanField(verbose_name='CPU Neck')),
                ('neck_io', models.BooleanField(verbose_name='IO Neck')),
                ('neck_memory', models.BooleanField(verbose_name='Memory Neck')),
                ('neck_net', models.BooleanField(verbose_name='Net Neck')),
                ('test_application', models.CharField(max_length=32, editable=False, default='Spark Terasort')),
                ('version', models.CharField(max_length=10, default='0.1', verbose_name='Application Version')),
                ('record_result_time', models.DateTimeField(verbose_name='Record Result Time', default=django.utils.timezone.now)),
                ('result_time', models.FloatField(verbose_name='Result - Time(s)')),
                ('data_size', models.FloatField(verbose_name='Data Size (GB)')),
                ('parition_size', models.PositiveSmallIntegerField(verbose_name='Partition Size')),
                ('processor_number', models.PositiveSmallIntegerField(verbose_name='Processor Number')),
                ('workers', models.PositiveIntegerField(verbose_name='Workers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SparkTerasortMachine',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('machine_side', models.CharField(max_length=32, default='server_side', verbose_name='Server/Client', choices=[('server_side', 'As a Server'), ('client_side', 'As a Client')])),
                ('machine_name', models.CharField(max_length=32, default='Habonaro', verbose_name='Machine Name', choices=[('Habonaro', 'Habonaro'), ('Palmetto', 'Palmetto'), ('S812L', 'S812L'), ('S822L', 'S822L'), ('X86_E5', 'X86 E5 Series')])),
                ('architecture_type', models.CharField(max_length=32, default='powerpc', verbose_name='Architecture', choices=[('x86', 'x86'), ('powerpc', 'powerpc'), ('arm64', 'arm64'), ('mips', 'mips')])),
                ('byte_order', models.CharField(max_length=32, default='big_endian', verbose_name='Litter or Big endian', choices=[('litter_endian', 'Litter Endian'), ('big_endian', 'Big Endian')])),
                ('cpu_frequency', models.FloatField(verbose_name='CPU Clock Rate (GHZ)')),
                ('l1_instruction', models.PositiveSmallIntegerField(verbose_name='L1 I-Cache (KB)')),
                ('l1_data', models.PositiveSmallIntegerField(verbose_name='L1 D-Cache (KB)')),
                ('l2', models.PositiveSmallIntegerField(verbose_name='L2 Cache (KB)')),
                ('l3', models.PositiveIntegerField(verbose_name='L3 Cache (KB)', blank=True, default=0)),
                ('l4', models.PositiveIntegerField(verbose_name='L4 Cache (KB)', blank=True, default=0)),
                ('memory', models.PositiveIntegerField(verbose_name='Memory (MB)')),
                ('os_type', models.CharField(max_length=64, default='Ubuntu 14.04.2', verbose_name='Operation System', choices=[('Ubuntu 14.04.1', 'Ubuntu 14.04.1'), ('Ubuntu 14.04.2', 'Ubuntu 14.04.2'), ('Ubuntu 14.04.3', 'Ubuntu 14.04.3'), ('Ubuntu 14.04.10', 'Ubuntu 14.04.10'), ('RHEL 7.0', 'RHEL 7.0'), ('CentOS 6.6', 'CentOS 6.6'), ('CentOS 6.7', 'CentOS 6.7'), ('CentOS 7.0', 'CentOS 7.0'), ('Fedora 22', 'Fedora 22'), ('PowerKVM 2.1.1', 'PowerKVM 2.1.1')])),
                ('kernel_version', models.CharField(max_length=64, default='3.16.0', verbose_name='Kernel Version', choices=[('2.6.32', '2.6.32'), ('3.10.0', '3.10.0'), ('3.10.53', '3.10.53'), ('3.10.89', '3.10.89'), ('3.13.0', '3.13.0'), ('3.16.0', '3.16.0'), ('3.19.0', '3.19.0'), ('4.0.4', '4.0.4'), ('4.1.0', '4.1.0')])),
                ('dependence_information', models.TextField(max_length=1024, blank=True, verbose_name='Dependency Instruction')),
                ('last_modify_time', models.DateTimeField(verbose_name='Last Modified Time', auto_now=True)),
                ('app_information', models.ForeignKey(to='performance.SparkTerasortInformation', verbose_name='SparkTerasort Information')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecCPUInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=32, verbose_name='Project Name')),
                ('project_id', models.CharField(max_length=32, verbose_name='Project ID')),
                ('cpu_type', models.CharField(max_length=32, default='CPU 1.0', verbose_name='CPU Type', choices=[('CPU 1.0', 'CPU 1.0'), ('CPU 1.1', 'CPU 1.1')])),
                ('reference_link', models.URLField(default='http://10.100.8.185:8090', verbose_name='Reference Link (Confluence)')),
                ('neck_cpu', models.BooleanField(verbose_name='CPU Neck')),
                ('neck_io', models.BooleanField(verbose_name='IO Neck')),
                ('neck_memory', models.BooleanField(verbose_name='Memory Neck')),
                ('neck_net', models.BooleanField(verbose_name='Net Neck')),
                ('test_application', models.CharField(max_length=32, editable=False, default='SPEC CPU')),
                ('version', models.CharField(max_length=10, default='0.1', verbose_name='Application Version')),
                ('record_result_time', models.DateTimeField(verbose_name='Record Result Time', default=django.utils.timezone.now)),
                ('result_int_rate_ratio', models.FloatField(verbose_name="Result - INT Rate Ratio's")),
                ('result_fp_rate_ratio', models.FloatField(verbose_name="Result - FP Rate Ratio's")),
                ('benchmarks', models.CharField(max_length=256, verbose_name='Benchmarks')),
                ('copies', models.PositiveSmallIntegerField(verbose_name='Copies')),
                ('smt_number', models.PositiveSmallIntegerField(verbose_name='SMT')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecCPUMachine',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('machine_side', models.CharField(max_length=32, default='server_side', verbose_name='Server/Client', choices=[('server_side', 'As a Server'), ('client_side', 'As a Client')])),
                ('machine_name', models.CharField(max_length=32, default='Habonaro', verbose_name='Machine Name', choices=[('Habonaro', 'Habonaro'), ('Palmetto', 'Palmetto'), ('S812L', 'S812L'), ('S822L', 'S822L'), ('X86_E5', 'X86 E5 Series')])),
                ('architecture_type', models.CharField(max_length=32, default='powerpc', verbose_name='Architecture', choices=[('x86', 'x86'), ('powerpc', 'powerpc'), ('arm64', 'arm64'), ('mips', 'mips')])),
                ('byte_order', models.CharField(max_length=32, default='big_endian', verbose_name='Litter or Big endian', choices=[('litter_endian', 'Litter Endian'), ('big_endian', 'Big Endian')])),
                ('cpu_frequency', models.FloatField(verbose_name='CPU Clock Rate (GHZ)')),
                ('l1_instruction', models.PositiveSmallIntegerField(verbose_name='L1 I-Cache (KB)')),
                ('l1_data', models.PositiveSmallIntegerField(verbose_name='L1 D-Cache (KB)')),
                ('l2', models.PositiveSmallIntegerField(verbose_name='L2 Cache (KB)')),
                ('l3', models.PositiveIntegerField(verbose_name='L3 Cache (KB)', blank=True, default=0)),
                ('l4', models.PositiveIntegerField(verbose_name='L4 Cache (KB)', blank=True, default=0)),
                ('memory', models.PositiveIntegerField(verbose_name='Memory (MB)')),
                ('os_type', models.CharField(max_length=64, default='Ubuntu 14.04.2', verbose_name='Operation System', choices=[('Ubuntu 14.04.1', 'Ubuntu 14.04.1'), ('Ubuntu 14.04.2', 'Ubuntu 14.04.2'), ('Ubuntu 14.04.3', 'Ubuntu 14.04.3'), ('Ubuntu 14.04.10', 'Ubuntu 14.04.10'), ('RHEL 7.0', 'RHEL 7.0'), ('CentOS 6.6', 'CentOS 6.6'), ('CentOS 6.7', 'CentOS 6.7'), ('CentOS 7.0', 'CentOS 7.0'), ('Fedora 22', 'Fedora 22'), ('PowerKVM 2.1.1', 'PowerKVM 2.1.1')])),
                ('kernel_version', models.CharField(max_length=64, default='3.16.0', verbose_name='Kernel Version', choices=[('2.6.32', '2.6.32'), ('3.10.0', '3.10.0'), ('3.10.53', '3.10.53'), ('3.10.89', '3.10.89'), ('3.13.0', '3.13.0'), ('3.16.0', '3.16.0'), ('3.19.0', '3.19.0'), ('4.0.4', '4.0.4'), ('4.1.0', '4.1.0')])),
                ('dependence_information', models.TextField(max_length=1024, blank=True, verbose_name='Dependency Instruction')),
                ('last_modify_time', models.DateTimeField(verbose_name='Last Modified Time', auto_now=True)),
                ('threads_per_core', models.PositiveSmallIntegerField(verbose_name='Thread(s) Per Core')),
                ('cores_per_socket', models.PositiveSmallIntegerField(verbose_name='Core(s) Per Socket')),
                ('socket_number', models.PositiveSmallIntegerField(verbose_name='Socket(s)')),
                ('numa_nodes', models.PositiveSmallIntegerField(verbose_name='NUMA Node(s)')),
                ('cpu_number', models.PositiveSmallIntegerField(verbose_name='CPU(s)')),
                ('app_information', models.ForeignKey(to='performance.SpecCPUInformation', verbose_name='SPEC CPU Information')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecjbbInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=32, verbose_name='Project Name')),
                ('project_id', models.CharField(max_length=32, verbose_name='Project ID')),
                ('cpu_type', models.CharField(max_length=32, default='CPU 1.0', verbose_name='CPU Type', choices=[('CPU 1.0', 'CPU 1.0'), ('CPU 1.1', 'CPU 1.1')])),
                ('reference_link', models.URLField(default='http://10.100.8.185:8090', verbose_name='Reference Link (Confluence)')),
                ('neck_cpu', models.BooleanField(verbose_name='CPU Neck')),
                ('neck_io', models.BooleanField(verbose_name='IO Neck')),
                ('neck_memory', models.BooleanField(verbose_name='Memory Neck')),
                ('neck_net', models.BooleanField(verbose_name='Net Neck')),
                ('test_application', models.CharField(max_length=32, editable=False, default='Spec jbb')),
                ('version', models.CharField(max_length=10, default='2005', verbose_name='Application Version')),
                ('record_result_time', models.DateTimeField(verbose_name='Record Result Time', default=django.utils.timezone.now)),
                ('result_bops', models.FloatField(verbose_name='Result - bops')),
                ('jbb_attachment', models.FileField(upload_to='%Y-%m-%d/%H-%M-%S', blank=True)),
                ('app_name', models.CharField(max_length=256, verbose_name='app name')),
                ('processor_number', models.PositiveSmallIntegerField(verbose_name='Processor Number')),
                ('jvm_parameter', models.CharField(max_length=512, verbose_name='JVM Parameter')),
                ('jvm_instances', models.PositiveSmallIntegerField(verbose_name='JVM Instances')),
                ('warehouses', models.PositiveIntegerField(verbose_name='WAREHOUSES')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecjbbMachine',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('machine_side', models.CharField(max_length=32, default='server_side', verbose_name='Server/Client', choices=[('server_side', 'As a Server'), ('client_side', 'As a Client')])),
                ('machine_name', models.CharField(max_length=32, default='Habonaro', verbose_name='Machine Name', choices=[('Habonaro', 'Habonaro'), ('Palmetto', 'Palmetto'), ('S812L', 'S812L'), ('S822L', 'S822L'), ('X86_E5', 'X86 E5 Series')])),
                ('architecture_type', models.CharField(max_length=32, default='powerpc', verbose_name='Architecture', choices=[('x86', 'x86'), ('powerpc', 'powerpc'), ('arm64', 'arm64'), ('mips', 'mips')])),
                ('byte_order', models.CharField(max_length=32, default='big_endian', verbose_name='Litter or Big endian', choices=[('litter_endian', 'Litter Endian'), ('big_endian', 'Big Endian')])),
                ('cpu_frequency', models.FloatField(verbose_name='CPU Clock Rate (GHZ)')),
                ('l1_instruction', models.PositiveSmallIntegerField(verbose_name='L1 I-Cache (KB)')),
                ('l1_data', models.PositiveSmallIntegerField(verbose_name='L1 D-Cache (KB)')),
                ('l2', models.PositiveSmallIntegerField(verbose_name='L2 Cache (KB)')),
                ('l3', models.PositiveIntegerField(verbose_name='L3 Cache (KB)', blank=True, default=0)),
                ('l4', models.PositiveIntegerField(verbose_name='L4 Cache (KB)', blank=True, default=0)),
                ('memory', models.PositiveIntegerField(verbose_name='Memory (MB)')),
                ('os_type', models.CharField(max_length=64, default='Ubuntu 14.04.2', verbose_name='Operation System', choices=[('Ubuntu 14.04.1', 'Ubuntu 14.04.1'), ('Ubuntu 14.04.2', 'Ubuntu 14.04.2'), ('Ubuntu 14.04.3', 'Ubuntu 14.04.3'), ('Ubuntu 14.04.10', 'Ubuntu 14.04.10'), ('RHEL 7.0', 'RHEL 7.0'), ('CentOS 6.6', 'CentOS 6.6'), ('CentOS 6.7', 'CentOS 6.7'), ('CentOS 7.0', 'CentOS 7.0'), ('Fedora 22', 'Fedora 22'), ('PowerKVM 2.1.1', 'PowerKVM 2.1.1')])),
                ('kernel_version', models.CharField(max_length=64, default='3.16.0', verbose_name='Kernel Version', choices=[('2.6.32', '2.6.32'), ('3.10.0', '3.10.0'), ('3.10.53', '3.10.53'), ('3.10.89', '3.10.89'), ('3.13.0', '3.13.0'), ('3.16.0', '3.16.0'), ('3.19.0', '3.19.0'), ('4.0.4', '4.0.4'), ('4.1.0', '4.1.0')])),
                ('dependence_information', models.TextField(max_length=1024, blank=True, verbose_name='Dependency Instruction')),
                ('last_modify_time', models.DateTimeField(verbose_name='Last Modified Time', auto_now=True)),
                ('app_information', models.ForeignKey(to='performance.SpecjbbInformation', verbose_name='Specjbb Information')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecjvmInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=32, verbose_name='Project Name')),
                ('project_id', models.CharField(max_length=32, verbose_name='Project ID')),
                ('cpu_type', models.CharField(max_length=32, default='CPU 1.0', verbose_name='CPU Type', choices=[('CPU 1.0', 'CPU 1.0'), ('CPU 1.1', 'CPU 1.1')])),
                ('reference_link', models.URLField(default='http://10.100.8.185:8090', verbose_name='Reference Link (Confluence)')),
                ('neck_cpu', models.BooleanField(verbose_name='CPU Neck')),
                ('neck_io', models.BooleanField(verbose_name='IO Neck')),
                ('neck_memory', models.BooleanField(verbose_name='Memory Neck')),
                ('neck_net', models.BooleanField(verbose_name='Net Neck')),
                ('test_application', models.CharField(max_length=32, editable=False, default='Spec jvm')),
                ('version', models.CharField(max_length=10, default='2008', verbose_name='Application Version')),
                ('record_result_time', models.DateTimeField(verbose_name='Record Result Time', default=django.utils.timezone.now)),
                ('result_bops', models.FloatField(verbose_name='Result - bops')),
                ('jvm_attachment', models.FileField(upload_to='%Y-%m-%d/%H-%M-%S', blank=True)),
                ('app_name', models.CharField(max_length=256, verbose_name='app name')),
                ('jvm_parameter', models.CharField(max_length=512, verbose_name='JVM Parameter')),
                ('specjvm_parameter', models.CharField(max_length=512, verbose_name='Spec JVM Parameter')),
                ('processor_number', models.PositiveSmallIntegerField(verbose_name='Processor Number')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecjvmMachine',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('machine_side', models.CharField(max_length=32, default='server_side', verbose_name='Server/Client', choices=[('server_side', 'As a Server'), ('client_side', 'As a Client')])),
                ('machine_name', models.CharField(max_length=32, default='Habonaro', verbose_name='Machine Name', choices=[('Habonaro', 'Habonaro'), ('Palmetto', 'Palmetto'), ('S812L', 'S812L'), ('S822L', 'S822L'), ('X86_E5', 'X86 E5 Series')])),
                ('architecture_type', models.CharField(max_length=32, default='powerpc', verbose_name='Architecture', choices=[('x86', 'x86'), ('powerpc', 'powerpc'), ('arm64', 'arm64'), ('mips', 'mips')])),
                ('byte_order', models.CharField(max_length=32, default='big_endian', verbose_name='Litter or Big endian', choices=[('litter_endian', 'Litter Endian'), ('big_endian', 'Big Endian')])),
                ('cpu_frequency', models.FloatField(verbose_name='CPU Clock Rate (GHZ)')),
                ('l1_instruction', models.PositiveSmallIntegerField(verbose_name='L1 I-Cache (KB)')),
                ('l1_data', models.PositiveSmallIntegerField(verbose_name='L1 D-Cache (KB)')),
                ('l2', models.PositiveSmallIntegerField(verbose_name='L2 Cache (KB)')),
                ('l3', models.PositiveIntegerField(verbose_name='L3 Cache (KB)', blank=True, default=0)),
                ('l4', models.PositiveIntegerField(verbose_name='L4 Cache (KB)', blank=True, default=0)),
                ('memory', models.PositiveIntegerField(verbose_name='Memory (MB)')),
                ('os_type', models.CharField(max_length=64, default='Ubuntu 14.04.2', verbose_name='Operation System', choices=[('Ubuntu 14.04.1', 'Ubuntu 14.04.1'), ('Ubuntu 14.04.2', 'Ubuntu 14.04.2'), ('Ubuntu 14.04.3', 'Ubuntu 14.04.3'), ('Ubuntu 14.04.10', 'Ubuntu 14.04.10'), ('RHEL 7.0', 'RHEL 7.0'), ('CentOS 6.6', 'CentOS 6.6'), ('CentOS 6.7', 'CentOS 6.7'), ('CentOS 7.0', 'CentOS 7.0'), ('Fedora 22', 'Fedora 22'), ('PowerKVM 2.1.1', 'PowerKVM 2.1.1')])),
                ('kernel_version', models.CharField(max_length=64, default='3.16.0', verbose_name='Kernel Version', choices=[('2.6.32', '2.6.32'), ('3.10.0', '3.10.0'), ('3.10.53', '3.10.53'), ('3.10.89', '3.10.89'), ('3.13.0', '3.13.0'), ('3.16.0', '3.16.0'), ('3.19.0', '3.19.0'), ('4.0.4', '4.0.4'), ('4.1.0', '4.1.0')])),
                ('dependence_information', models.TextField(max_length=1024, blank=True, verbose_name='Dependency Instruction')),
                ('last_modify_time', models.DateTimeField(verbose_name='Last Modified Time', auto_now=True)),
                ('app_information', models.ForeignKey(to='performance.SpecjvmInformation', verbose_name='Specjvm Information')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SplashInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=32, verbose_name='Project Name')),
                ('project_id', models.CharField(max_length=32, verbose_name='Project ID')),
                ('cpu_type', models.CharField(max_length=32, default='CPU 1.0', verbose_name='CPU Type', choices=[('CPU 1.0', 'CPU 1.0'), ('CPU 1.1', 'CPU 1.1')])),
                ('reference_link', models.URLField(default='http://10.100.8.185:8090', verbose_name='Reference Link (Confluence)')),
                ('neck_cpu', models.BooleanField(verbose_name='CPU Neck')),
                ('neck_io', models.BooleanField(verbose_name='IO Neck')),
                ('neck_memory', models.BooleanField(verbose_name='Memory Neck')),
                ('neck_net', models.BooleanField(verbose_name='Net Neck')),
                ('test_application', models.CharField(max_length=32, editable=False, default='Splash')),
                ('version', models.CharField(max_length=10, default='2.0', verbose_name='Application Version')),
                ('record_result_time', models.DateTimeField(verbose_name='Record Result Time', default=django.utils.timezone.now)),
                ('result_time', models.FloatField(verbose_name='Result - Time(us)')),
                ('app_name', models.CharField(max_length=256, verbose_name='app name')),
                ('problem_size', models.CharField(max_length=256, verbose_name='Problem Size')),
                ('processor_number', models.PositiveSmallIntegerField(verbose_name='Processor Number')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SplashMachine',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('machine_side', models.CharField(max_length=32, default='server_side', verbose_name='Server/Client', choices=[('server_side', 'As a Server'), ('client_side', 'As a Client')])),
                ('machine_name', models.CharField(max_length=32, default='Habonaro', verbose_name='Machine Name', choices=[('Habonaro', 'Habonaro'), ('Palmetto', 'Palmetto'), ('S812L', 'S812L'), ('S822L', 'S822L'), ('X86_E5', 'X86 E5 Series')])),
                ('architecture_type', models.CharField(max_length=32, default='powerpc', verbose_name='Architecture', choices=[('x86', 'x86'), ('powerpc', 'powerpc'), ('arm64', 'arm64'), ('mips', 'mips')])),
                ('byte_order', models.CharField(max_length=32, default='big_endian', verbose_name='Litter or Big endian', choices=[('litter_endian', 'Litter Endian'), ('big_endian', 'Big Endian')])),
                ('cpu_frequency', models.FloatField(verbose_name='CPU Clock Rate (GHZ)')),
                ('l1_instruction', models.PositiveSmallIntegerField(verbose_name='L1 I-Cache (KB)')),
                ('l1_data', models.PositiveSmallIntegerField(verbose_name='L1 D-Cache (KB)')),
                ('l2', models.PositiveSmallIntegerField(verbose_name='L2 Cache (KB)')),
                ('l3', models.PositiveIntegerField(verbose_name='L3 Cache (KB)', blank=True, default=0)),
                ('l4', models.PositiveIntegerField(verbose_name='L4 Cache (KB)', blank=True, default=0)),
                ('memory', models.PositiveIntegerField(verbose_name='Memory (MB)')),
                ('os_type', models.CharField(max_length=64, default='Ubuntu 14.04.2', verbose_name='Operation System', choices=[('Ubuntu 14.04.1', 'Ubuntu 14.04.1'), ('Ubuntu 14.04.2', 'Ubuntu 14.04.2'), ('Ubuntu 14.04.3', 'Ubuntu 14.04.3'), ('Ubuntu 14.04.10', 'Ubuntu 14.04.10'), ('RHEL 7.0', 'RHEL 7.0'), ('CentOS 6.6', 'CentOS 6.6'), ('CentOS 6.7', 'CentOS 6.7'), ('CentOS 7.0', 'CentOS 7.0'), ('Fedora 22', 'Fedora 22'), ('PowerKVM 2.1.1', 'PowerKVM 2.1.1')])),
                ('kernel_version', models.CharField(max_length=64, default='3.16.0', verbose_name='Kernel Version', choices=[('2.6.32', '2.6.32'), ('3.10.0', '3.10.0'), ('3.10.53', '3.10.53'), ('3.10.89', '3.10.89'), ('3.13.0', '3.13.0'), ('3.16.0', '3.16.0'), ('3.19.0', '3.19.0'), ('4.0.4', '4.0.4'), ('4.1.0', '4.1.0')])),
                ('dependence_information', models.TextField(max_length=1024, blank=True, verbose_name='Dependency Instruction')),
                ('last_modify_time', models.DateTimeField(verbose_name='Last Modified Time', auto_now=True)),
                ('app_information', models.ForeignKey(to='performance.SplashInformation', verbose_name='Splash Information')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TpccInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=32, verbose_name='Project Name')),
                ('project_id', models.CharField(max_length=32, verbose_name='Project ID')),
                ('cpu_type', models.CharField(max_length=32, default='CPU 1.0', verbose_name='CPU Type', choices=[('CPU 1.0', 'CPU 1.0'), ('CPU 1.1', 'CPU 1.1')])),
                ('reference_link', models.URLField(default='http://10.100.8.185:8090', verbose_name='Reference Link (Confluence)')),
                ('neck_cpu', models.BooleanField(verbose_name='CPU Neck')),
                ('neck_io', models.BooleanField(verbose_name='IO Neck')),
                ('neck_memory', models.BooleanField(verbose_name='Memory Neck')),
                ('neck_net', models.BooleanField(verbose_name='Net Neck')),
                ('test_application', models.CharField(max_length=32, editable=False, default='TPC-C')),
                ('version', models.CharField(max_length=10, default='0.1', verbose_name='Application Version')),
                ('record_result_time', models.DateTimeField(verbose_name='Record Result Time', default=django.utils.timezone.now)),
                ('result_tpmc', models.FloatField(verbose_name='Result - tpmC')),
                ('warehouses', models.PositiveIntegerField(verbose_name='WAREHOUSES')),
                ('terminals', models.PositiveSmallIntegerField(verbose_name='TERMINALS')),
                ('run_time', models.FloatField(verbose_name='RUN_TIME')),
                ('network_bandwidth', models.PositiveSmallIntegerField(verbose_name='Network Bandwidth (Mbps)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TpccMachine',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('machine_side', models.CharField(max_length=32, default='server_side', verbose_name='Server/Client', choices=[('server_side', 'As a Server'), ('client_side', 'As a Client')])),
                ('machine_name', models.CharField(max_length=32, default='Habonaro', verbose_name='Machine Name', choices=[('Habonaro', 'Habonaro'), ('Palmetto', 'Palmetto'), ('S812L', 'S812L'), ('S822L', 'S822L'), ('X86_E5', 'X86 E5 Series')])),
                ('architecture_type', models.CharField(max_length=32, default='powerpc', verbose_name='Architecture', choices=[('x86', 'x86'), ('powerpc', 'powerpc'), ('arm64', 'arm64'), ('mips', 'mips')])),
                ('byte_order', models.CharField(max_length=32, default='big_endian', verbose_name='Litter or Big endian', choices=[('litter_endian', 'Litter Endian'), ('big_endian', 'Big Endian')])),
                ('cpu_frequency', models.FloatField(verbose_name='CPU Clock Rate (GHZ)')),
                ('l1_instruction', models.PositiveSmallIntegerField(verbose_name='L1 I-Cache (KB)')),
                ('l1_data', models.PositiveSmallIntegerField(verbose_name='L1 D-Cache (KB)')),
                ('l2', models.PositiveSmallIntegerField(verbose_name='L2 Cache (KB)')),
                ('l3', models.PositiveIntegerField(verbose_name='L3 Cache (KB)', blank=True, default=0)),
                ('l4', models.PositiveIntegerField(verbose_name='L4 Cache (KB)', blank=True, default=0)),
                ('memory', models.PositiveIntegerField(verbose_name='Memory (MB)')),
                ('os_type', models.CharField(max_length=64, default='Ubuntu 14.04.2', verbose_name='Operation System', choices=[('Ubuntu 14.04.1', 'Ubuntu 14.04.1'), ('Ubuntu 14.04.2', 'Ubuntu 14.04.2'), ('Ubuntu 14.04.3', 'Ubuntu 14.04.3'), ('Ubuntu 14.04.10', 'Ubuntu 14.04.10'), ('RHEL 7.0', 'RHEL 7.0'), ('CentOS 6.6', 'CentOS 6.6'), ('CentOS 6.7', 'CentOS 6.7'), ('CentOS 7.0', 'CentOS 7.0'), ('Fedora 22', 'Fedora 22'), ('PowerKVM 2.1.1', 'PowerKVM 2.1.1')])),
                ('kernel_version', models.CharField(max_length=64, default='3.16.0', verbose_name='Kernel Version', choices=[('2.6.32', '2.6.32'), ('3.10.0', '3.10.0'), ('3.10.53', '3.10.53'), ('3.10.89', '3.10.89'), ('3.13.0', '3.13.0'), ('3.16.0', '3.16.0'), ('3.19.0', '3.19.0'), ('4.0.4', '4.0.4'), ('4.1.0', '4.1.0')])),
                ('dependence_information', models.TextField(max_length=1024, blank=True, verbose_name='Dependency Instruction')),
                ('last_modify_time', models.DateTimeField(verbose_name='Last Modified Time', auto_now=True)),
                ('app_information', models.ForeignKey(to='performance.TpccInformation', verbose_name='TPC-C Information')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebServingInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=32, verbose_name='Project Name')),
                ('project_id', models.CharField(max_length=32, verbose_name='Project ID')),
                ('cpu_type', models.CharField(max_length=32, default='CPU 1.0', verbose_name='CPU Type', choices=[('CPU 1.0', 'CPU 1.0'), ('CPU 1.1', 'CPU 1.1')])),
                ('reference_link', models.URLField(default='http://10.100.8.185:8090', verbose_name='Reference Link (Confluence)')),
                ('neck_cpu', models.BooleanField(verbose_name='CPU Neck')),
                ('neck_io', models.BooleanField(verbose_name='IO Neck')),
                ('neck_memory', models.BooleanField(verbose_name='Memory Neck')),
                ('neck_net', models.BooleanField(verbose_name='Net Neck')),
                ('test_application', models.CharField(max_length=32, editable=False, default='WebServing')),
                ('version', models.CharField(max_length=10, default='0.1', verbose_name='Application Version')),
                ('record_result_time', models.DateTimeField(verbose_name='Record Result Time', default=django.utils.timezone.now)),
                ('result_ops', models.FloatField(verbose_name='Result - OPS')),
                ('result_passed', models.BooleanField(verbose_name='Result - PASSED')),
                ('result_warnings', models.BooleanField(verbose_name='Result - WARNINGS')),
                ('result_errors', models.BooleanField(verbose_name='Result - ERRORS')),
                ('warm_up', models.PositiveSmallIntegerField(verbose_name='Warm Up')),
                ('con_users', models.PositiveSmallIntegerField(verbose_name='CON Users')),
                ('pm_static', models.BooleanField(verbose_name='PM Staic')),
                ('pm_max_connections', models.PositiveSmallIntegerField(verbose_name='PM Max Connections')),
                ('sql_max_connections', models.PositiveSmallIntegerField(verbose_name='SQL Max Connections')),
                ('worker_processes', models.PositiveSmallIntegerField(verbose_name='Worker Processes')),
                ('worker_connection', models.PositiveSmallIntegerField(verbose_name='Worker Connection')),
                ('network_bandwidth', models.PositiveSmallIntegerField(verbose_name='Network Bandwidth (Mbps)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebServingMachine',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('os_type', models.CharField(max_length=64, default='Ubuntu 14.04.2', verbose_name='Operation System', choices=[('Ubuntu 14.04.1', 'Ubuntu 14.04.1'), ('Ubuntu 14.04.2', 'Ubuntu 14.04.2'), ('Ubuntu 14.04.3', 'Ubuntu 14.04.3'), ('Ubuntu 14.04.10', 'Ubuntu 14.04.10'), ('RHEL 7.0', 'RHEL 7.0'), ('CentOS 6.6', 'CentOS 6.6'), ('CentOS 6.7', 'CentOS 6.7'), ('CentOS 7.0', 'CentOS 7.0'), ('Fedora 22', 'Fedora 22'), ('PowerKVM 2.1.1', 'PowerKVM 2.1.1')])),
                ('kernel_version', models.CharField(max_length=64, default='3.16.0', verbose_name='Kernel Version', choices=[('2.6.32', '2.6.32'), ('3.10.0', '3.10.0'), ('3.10.53', '3.10.53'), ('3.10.89', '3.10.89'), ('3.13.0', '3.13.0'), ('3.16.0', '3.16.0'), ('3.19.0', '3.19.0'), ('4.0.4', '4.0.4'), ('4.1.0', '4.1.0')])),
                ('dependence_information', models.TextField(max_length=1024, blank=True, verbose_name='Dependency Instruction')),
                ('machine_side', models.CharField(max_length=32, default='client_side', verbose_name='Machine Role', choices=[('frontend', 'As a Frontend'), ('backend', 'As a Backend'), ('client_side', 'As a Client')])),
                ('machine_name', models.CharField(max_length=32, default='Habonaro', verbose_name='Machine Name', choices=[('Habonaro', 'Habonaro'), ('Palmetto', 'Palmetto'), ('S812L', 'S812L'), ('S822L', 'S822L'), ('X86_E5', 'X86 E5 Series')])),
                ('architecture_type', models.CharField(max_length=32, default='powerpc', verbose_name='Architecture', choices=[('x86', 'x86'), ('powerpc', 'powerpc'), ('arm64', 'arm64'), ('mips', 'mips')])),
                ('byte_order', models.CharField(max_length=32, default='big_endian', verbose_name='Litter or Big endian', choices=[('litter_endian', 'Litter Endian'), ('big_endian', 'Big Endian')])),
                ('cpu_frequency', models.FloatField(verbose_name='CPU Clock Rate (GHZ)')),
                ('l1_instruction', models.PositiveSmallIntegerField(verbose_name='L1 I-Cache (KB)')),
                ('l1_data', models.PositiveSmallIntegerField(verbose_name='L1 D-Cache (KB)')),
                ('l2', models.PositiveSmallIntegerField(verbose_name='L2 Cache (KB)')),
                ('l3', models.PositiveIntegerField(verbose_name='L3 Cache (KB)', blank=True, default=0)),
                ('half_l3', models.BooleanField(verbose_name='Half L3 Cache')),
                ('l4', models.PositiveIntegerField(verbose_name='L4 Cache (KB)', blank=True, default=0)),
                ('memory', models.PositiveIntegerField(verbose_name='Memory (MB)')),
                ('last_modify_time', models.DateTimeField(verbose_name='Last Modified Time', auto_now=True)),
                ('app_information', models.ForeignKey(to='performance.WebServingInformation', verbose_name='WebServing Information')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
